namespace SpriteKind {
    export const Key = SpriteKind.create()
    export const Ghoul = SpriteKind.create()
    export const Montser = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Ghoul, function (sprite, otherSprite) {
    game.splash("The ghoul got you!", "Go back!")
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairEast)
    otherSprite.destroy()
    tiles.placeOnRandomTile(ghoul, sprites.dungeon.floorLight0)
    ghoul.setVelocity(randint(-20, 20), randint(-20, 20))
    ghoul.setFlag(SpriteFlag.BounceOnWall, true)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile4`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile7`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava0, function (sprite, location) {
    game.splash("You fell in lava", "Go back!")
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairWest)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile3`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile11`, function (sprite, location) {
    if (KeyPosition == 1) {
        game.splash("You escaped the dungeon!")
        game.over(true)
    }
})
function loadLevel (level: number) {
    for (let value of sprites.allOfKind(SpriteKind.Montser)) {
        value.destroy()
    }
    for (let value of sprites.allOfKind(SpriteKind.Ghoul)) {
        value.destroy()
    }
    for (let value of sprites.allOfKind(SpriteKind.Key)) {
        value.destroy()
    }
    if (level == 1) {
        tiles.setTilemap(tilemap`level`)
        tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairWest)
        for (let index = 0; index < 4; index++) {
            ghoul = sprites.create(img`
                ........................
                ........................
                ........................
                ........................
                .........f..............
                ............f...........
                .......5f...............
                .......5555f............
                .......5555.............
                .......5555.............
                ........fff.............
                ........fffff...........
                ........fff.............
                .........ff.............
                ..........f.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `, SpriteKind.Ghoul)
            tiles.placeOnRandomTile(ghoul, sprites.dungeon.floorLight0)
            ghoul.setVelocity(randint(-20, 20), randint(-20, 20))
            ghoul.setFlag(SpriteFlag.BounceOnWall, true)
        }
        for (let value of tiles.getTilesByType(sprites.dungeon.floorLight1)) {
            monster = sprites.create(img`
                . . f f f . . . . . . . . f f f 
                . f f c c . . . . . . f c b b c 
                f f c c . . . . . . f c b b c . 
                f c f c . . . . . . f b c c c . 
                f f f c c . c c . f c b b c c . 
                f f c 3 c c 3 c c f b c b b c . 
                f f b 3 b c 3 b c f b c c b c . 
                . c 1 b b b 1 b c b b c c c . . 
                . c 1 b b b 1 b b c c c c . . . 
                c b b b b b b b b b c c . . . . 
                c b 1 f f 1 c b b b b f . . . . 
                f f 1 f f 1 f b b b b f c . . . 
                f f 2 2 2 2 f b b b b f c c . . 
                . f 2 2 2 2 b b b b c f . . . . 
                . . f b b b b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                `, SpriteKind.Montser)
            tiles.placeOnTile(monster, value)
            monster.setVelocity(30, 0)
            monster.setFlag(SpriteFlag.BounceOnWall, true)
        }
    } else {
        tiles.setTilemap(tilemap`level`)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Key, function (sprite, otherSprite) {
    KeyPosition = 1
    Key2.setPosition(0, 0)
    Key2.setFlag(SpriteFlag.StayInScreen, true)
    tiles.setWallAt(tiles.getTileLocation(13, 0), false)
    tiles.setWallAt(tiles.getTileLocation(14, 0), false)
    tiles.setWallAt(tiles.getTileLocation(15, 0), false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    Key2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . 5 5 . . . 5 5 . . . . . 
        . . . . 5 5 . . . 5 5 . . . . . 
        . . . . 5 5 . . . 5 5 . . . . . 
        . . . . . 5 5 5 5 5 . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 5 . . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 5 5 . . . . . . 
        . . . . . . . 5 . . . . . . . . 
        . . . . . . . 5 5 5 . . . . . . 
        `, SpriteKind.Key)
    tiles.placeOnRandomTile(Key2, sprites.dungeon.chestClosed)
    tiles.setTileAt(location, sprites.dungeon.floorLight0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile8`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile1`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile5`, function (sprite, location) {
    game.over(false)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.hazardLava1, function (sprite, location) {
    game.splash("You fell in lava", "Go back!")
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairWest)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile6`, function (sprite, location) {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Montser, function (sprite, otherSprite) {
    game.splash("The monster got you", "Go back!")
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairWest)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile9`, function (sprite, location) {
    game.over(false)
})
let Key2: Sprite = null
let monster: Sprite = null
let KeyPosition = 0
let ghoul: Sprite = null
let mySprite: Sprite = null
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 50, 50)
scene.cameraFollowSprite(mySprite)
loadLevel(1)
game.onUpdate(function () {
    if (KeyPosition == 1) {
        Key2.setPosition(0, 0)
    }
})
game.onUpdate(function () {
    mySprite.setImage(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `)
    if (mySprite.vx < 0) {
        mySprite.setImage(img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f1111111dbf......
            ......fd1111111ddf......
            ......fd111111dddf......
            ......fd111ddddddf......
            ......fd111ddddddf......
            ......fd1dddddddbf......
            ......fd1dfbddbbff......
            ......fbddfcdbbcf.......
            .....ffffccddbfff.......
            ....fcb1bbbfcffff.......
            ....f1b1dcffffffff......
            ....fdfdf..ffffffffff...
            .....f.f.....ffffff.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
    } else if (mySprite.vx > 0) {
        mySprite.setImage(img`
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            ......fbd1111111f.......
            ......fdd1111111df......
            ......fddd111111df......
            ......fdddddd111df......
            ......fdddddd111df......
            ......fbddddddd1df......
            ......ffbbddbfd1df......
            .......fcbbdcfddbf......
            .......fffbddccffff.....
            .......ffffcfbbb1bcf....
            ......ffffffffcd1b1f....
            ...ffffffffff..fdfdf....
            .....ffffff.....f.f.....
            ........................
            ........................
            ........................
            ........................
            ........................
            `)
    }
})
game.onUpdate(function () {
    for (let value2 of sprites.allOfKind(SpriteKind.Montser)) {
        value2.setImage(img`
            . . f f f . . . . . . . . f f f 
            . f f c c . . . . . . f c b b c 
            f f c c . . . . . . f c b b c . 
            f c f c . . . . . . f b c c c . 
            f f f c c . c c . f c b b c c . 
            f f c 3 c c 3 c c f b c b b c . 
            f f b 3 b c 3 b c f b c c b c . 
            . c 1 b b b 1 b c b b c c c . . 
            . c 1 b b b 1 b b c c c c . . . 
            c b b b b b b b b b c c . . . . 
            c b 1 f f 1 c b b b b f . . . . 
            f f 1 f f 1 f b b b b f c . . . 
            f f 2 2 2 2 f b b b b f c c . . 
            . f 2 2 2 2 b b b b c f . . . . 
            . . f b b b b b b c f . . . . . 
            . . . f f f f f f f . . . . . . 
            `)
        if (value2.vx > 0) {
            value2.image.flipX()
        }
    }
})
